version: '3.7'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: mydatabase
    ports: 
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
